### ISSUE TITLE
Improve User Experience and Interface Design

### ISSUE THREAD

**Issue by maddaicita** [maddaicita/ClassMateBot-1.1#1]
Enhance the bot's user interaction by making commands more intuitive and responses clearer.
Skills Needed: Basic understanding of user experience design and Discord bot commands.
Tools: Python for scripting, Discord API.

**Comment by greyfiles** [comment]
~~As a part of this enhancement, descriptions for the arguments for all commands should be added. Right now, the help page prints out "No description given" for all arguments.~~ This has been added to issue number 2

**Comment by greyfiles** [comment]
There are many instances in the code where error cases or side cases result in no output from the bot at all. This needs to be addressed to always respond to the user. Additionally, error outputs often give no recommendation on how to correctly complete the command which would help to improve the user experience.

**Comment by greyfiles** [comment]
Some command names use camel case while some are all lower case. The commands are case sensitive, so a uniform convention needs to be established to improve the user experience.
