### ISSUE TITLE
Extended Help and Tutorial Commands

### ISSUE THREAD

**Issue by maddaicita** [maddaicita/ClassMateBot-1.1#2]
Develop a comprehensive help system or tutorial commands that guide users through the bot's functionalities.
Skills Needed: Ability to write clear, concise instructional text.
Tools: Python for bot command scripting.

**Comment by greyfiles** [comment]
As a part of this enhancement, descriptions for the arguments for all commands should be added. Right now, the help page prints out "No description given" for all arguments.
