### ISSUE TITLE
Accessibility Improvements

### ISSUE THREAD

**Issue by maddaicita** [maddaicita/ClassMateBot-1.1#4]
Make the bot more accessible by adding features like text-to-speech or command aliases for ease of use.
Skills Needed: Understanding of accessibility standards.
Tools: Python libraries for text-to-speech, Discord API.

**Comment by AbsolLoot** [comment]
I'm going to treat this issue as more of an epic, rather than necessarily a single issue for both, other issues will be created related to this, and this issue will be marked as done once I'm finished with this area of work.

**Comment by AbsolLoot** [comment]
resolved in aliases, rest is out of scope
